Add Twitter and Discord to community links
minetest/minetest.github.io pull request #224
Opened 2020-12-23 00:25 UTC by GreenXenith

2020-12-23 13:38 UTC, celeron55 commented
So, I think we need to officialize open alternatives at the same time.

For Discord it would be Matrix. It's not clear what the room or community should be, but the current link to the current room is https://matrix.to/#/+minetest:tchncs.de

For Twitter, I guess it has to be Mastodon. Do we have anything on Mastodon? If not, does someone want to set that up?

2020-12-23 13:39 UTC, rubenwardy commented
Yes, I run this account on mastodon: http://fosstodon.org/minetest

2020-12-23 23:58 UTC, GreenXenith commented
I had intended to include Mastodon but for some reason I couldn't find the official user at the time.

Mastodon and Matrix have been added. I also split the community list into community and social mainly for size reasons (loosely sorted by activity). Feel free to suggest a different categorization.

2021-01-26 18:10 UTC, celeron55 requested changes
I'm ok with the content, altough what about listing the non-proprietary ones on top? I don't want it to feel like we're promoting Reddit, Twitter and Discord. Looks-wise I don't care.

2021-02-05 22:20 UTC, GreenXenith commented
Reordered socials to promote FOSS platforms. Order based mostly on color.
![image](https://user-images.githubusercontent.com/24834740/107095182-2c05f580-67bd-11eb-9fd3-dc7f789ec84b.png)
Footer list has been reordered to reflect changes.

2021-02-23 20:30 UTC, celeron55 approved these changes
Looks good in the screenshot. Can I request someone to look through the code and merge if it's reasonable? I'm not exactly familiar with Jekyll.

2021-02-23 20:35 UTC, rubenwardy commented on _includes/footer.html
> +          <li><a href="https://fosstodon.org/@minetest">Mastodon</a></li>
```suggestion
          <li><a href="https://fosstodon.org/@minetest" rel="me">Mastodon</a></li>
```

2021-02-23 20:41 UTC, Calinou approved these changes
Thanks!

2021-02-23 20:43 UTC, merged